
services:
  - type: web
    name: code-diagramerz
    env: docker
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    dockerfilePath: ./Dockerfile
    region: singapore
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 8080
    disk:
      name: data
      mountPath: /data
      sizeGB: 1